"""add customer profile status field

Revision ID: 4cb12b38ff84
Revises: 8c4a2b1f0e3d
Create Date: 2026-04-23 10:21:29.161120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4cb12b38ff84'
down_revision: Union[str, Sequence[str], None] = '8c4a2b1f0e3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('profile_status', sa.Integer(), server_default='0', nullable=False))
    # op.drop_index(op.f('idx_customer_id'), table_name='orders')
    # op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    op.alter_column('raw_customers', 'label',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               type_=sa.String(length=200),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('raw_customers', 'profile_status',
               existing_type=mysql.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'0'"))
    op.alter_column('raw_customers', 'label',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=255),
               existing_nullable=True)
    op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    op.create_index(op.f('idx_customer_id'), 'orders', ['customer_id'], unique=False)
    op.drop_column('customers', 'profile_status')
    # ### end Alembic commands ###
