"""make_phone_nullable

Revision ID: 516f31198606
Revises: 
Create Date: 2026-04-23 08:55:07.450053

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '516f31198606'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    tables_res = conn.execute(sa.text("SHOW TABLES"))
    tables = [row[0] for row in tables_res]

    # ### commands auto generated by Alembic - please adjust! ###
    if 'test_users' in tables:
        try:
            op.drop_index(op.f('ix_test_users_id'), table_name='test_users')
            op.drop_index(op.f('username'), table_name='test_users')
            op.drop_table('test_users')
        except: pass
    
    if 'transfer_customer_link' in tables:
        try: op.drop_table('transfer_customer_link')
        except: pass
    
    try: op.drop_constraint(op.f('business_transfers_ibfk_1'), 'business_transfers', type_='foreignkey')
    except: pass
    try: op.drop_constraint(op.f('business_transfers_ibfk_2'), 'business_transfers', type_='foreignkey')
    except: pass
    try: op.drop_constraint(op.f('fk_transfer_customer'), 'business_transfers', type_='foreignkey')
    except: pass

    op.create_foreign_key(None, 'business_transfers', 'users', ['from_user_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key(None, 'business_transfers', 'users', ['to_user_id'], ['id'], onupdate='CASCADE')
    
    try: op.drop_column('business_transfers', 'target_customer_id')
    except: pass

    op.alter_column('customers', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=True)
    
    # op.drop_index(op.f('idx_customer_id'), table_name='orders')
    # op.create_index(op.f('ix_orders_customer_id'), 'orders', ['customer_id'], unique=False)
    
    op.alter_column('sync_failures', 'supplier_id',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               type_=sa.String(length=50),
               existing_nullable=False)
    op.create_index(op.f('ix_user_customer_relations_customer_id'), 'user_customer_relations', ['customer_id'], unique=False)
    op.create_index(op.f('ix_user_customer_relations_user_id'), 'user_customer_relations', ['user_id'], unique=False)
    
    try: op.drop_constraint(op.f('user_customer_relations_ibfk_2'), 'user_customer_relations', type_='foreignkey')
    except: pass
    try: op.drop_constraint(op.f('fk_rel_username'), 'user_customer_relations', type_='foreignkey')
    except: pass
    try: op.drop_constraint(op.f('user_customer_relations_ibfk_1'), 'user_customer_relations', type_='foreignkey')
    except: pass

    op.create_foreign_key(None, 'user_customer_relations', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_customer_relations', 'customers', ['customer_id'], ['id'], ondelete='CASCADE')
    
    try: op.drop_column('user_customer_relations', 'username')
    except: pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_customer_relations', sa.Column('username', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=True))
    op.drop_constraint(None, 'user_customer_relations', type_='foreignkey')
    op.drop_constraint(None, 'user_customer_relations', type_='foreignkey')
    op.create_foreign_key(op.f('user_customer_relations_ibfk_1'), 'user_customer_relations', 'users', ['user_id'], ['id'])
    op.create_foreign_key(op.f('fk_rel_username'), 'user_customer_relations', 'users', ['username'], ['username'], onupdate='CASCADE')
    # op.create_foreign_key(op.f('user_customer_relations_ibfk_2'), 'user_customer_relations', 'customers', ['customer_id'], ['id'])
    op.drop_index(op.f('ix_user_customer_relations_user_id'), table_name='user_customer_relations')
    op.drop_index(op.f('ix_user_customer_relations_customer_id'), table_name='user_customer_relations')
    op.alter_column('sync_failures', 'supplier_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               existing_nullable=False)
    # op.drop_index(op.f('ix_orders_customer_id'), table_name='orders')
    # op.create_index(op.f('idx_customer_id'), 'orders', ['customer_id'], unique=False)
    op.alter_column('customers', 'phone',
               existing_type=mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100),
               nullable=False)
    op.add_column('business_transfers', sa.Column('target_customer_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'business_transfers', type_='foreignkey')
    op.drop_constraint(None, 'business_transfers', type_='foreignkey')
    # op.create_foreign_key(op.f('fk_transfer_customer'), 'business_transfers', 'customers', ['target_customer_id'], ['id'], onupdate='CASCADE')
    op.create_foreign_key(op.f('business_transfers_ibfk_2'), 'business_transfers', 'users', ['to_user_id'], ['id'])
    op.create_foreign_key(op.f('business_transfers_ibfk_1'), 'business_transfers', 'users', ['from_user_id'], ['id'])
    # ### end Alembic commands ###
